== Release notes for package dwh-etl-1.0.0.deb

. <<1.0.0-RN1>>
. <<1.0.0-RN2>>
. <<1.0.0-RN3>>


== Release notes for package dwh-etl-1.0.0.deb

[id="1.0.0-RN1"]
=== "mdx" removed from package name, directory names and file names

In order to simplify the support for different use cases, the identifier "mdx"
has been removed throughout this product. As a result, package versioning has
been reset. These release notes are for package:

 dwh-etl-1.0.0.deb

The _previous_ release of this software was packaged as:

 mdx-dwh-etl-1.6.0.deb

Because the "mdx" identifier has also been removed from directory and file names
that are installed by the package `dwh-etl-1.0.0.deb`, there are some tasks that
must be performed manually to migrate settings that were used with the old 
`mdx-dwh-etl` package so that they will be found by the the new `dwh-etl` 
package. These tasks are described in the following sections. They are only 
required if you are _upgrading_ an existing installation of the the 
`mdx-dwh-etl` package.

==== Installation directory of the Q-Free ETL toolkit for PDI has been changed

These files were previously installed in:

 /opt/dwh/mdx-dwh-etl/

They will now be installed in:

 /opt/dwh/dwh-etl/

The directory `/opt/dwh/mdx-dwh-etl/` can be deleted, as it is no longer needed.

==== Directory containing the configuration files has been changed

The configuration files were previously installed in:

 /etc/dwh/mdx-dwh-etl/

They will now be installed in:

 /etc/dwh/dwh-etl/

The *_previous_* configuration files were:

 /etc/dwh/mdx-dwh-etl/q-free/dwh-qfree.properties
 /etc/dwh/mdx-dwh-etl/config/dwh.properties

The *_new_* configuration files are:

 /etc/dwh/dwh-etl/q-free/dwh-qfree.properties
 /etc/dwh/dwh-etl/config/dwh.properties

In order preserve your current configuration parameters, you must manually 
transfer them from the old configuration files to the new configuration files.
The easiest way to do this is to simply *_replace_* the newly installed 
configuration files (which contain default configuration settings) with the old 
ones (that contain your customized settings) with:

 $ sudo su -l etl    # must be done as user "etl"
 $ cp /etc/dwh/mdx-dwh-etl/q-free/dwh-qfree.properties \
      /etc/dwh/dwh-etl/q-free/dwh-qfree.properties
 $ cp /etc/dwh/mdx-dwh-etl/config/dwh.properties /etc/dwh/dwh-etl/config/dwh.properties

After the contents of the previous configuration files have been transferred
to the new configuration files, directory `/opt/dwh/mdx-dwh-etl/` can be 
deleted, as it is no longer needed.

==== Name of cron settings file has been changed

The default `cron` settings file that is installed by the `dwh-etl` package is 
now named "dwh-etl" (the name previously used was "mdx-dwh-etl"). To avoid 
confusion, it is recommended to rename the previously settings file (that 
contains your customized schedule) to use the new file name. This can be done by 
executing: 
 
 sudo mv /etc/cron.d/mdx-dwh-etl /etc/cron.d/dwh-etl


==== Environment variable DWH_HOME must be updated

The environment variable `DWH_HOME` for the `etl` user must be updated to 
reflect the new installation directory.

Edit the `.profile` file in the home directory of the `etl` user and replace the
line:

 export DWH_HOME=/opt/dwh/mdx-dwh-etl

with:

 export DWH_HOME=/opt/dwh/dwh-etl

Other occurrences of the string "`mdx-`" in the comments can also be deleted to
avoid confusion in the future.

After this change is made, the data warehouse server should be restarted to
ensure that the new value is used.


[id="1.0.0-RN2"]
=== Support for the TDP star schema data mart has been removed

Support for the TDP star schema data mart has been removed from the data 
warehouse. All reports should be generated by querying the tables in the data
warehouse that are mirrored from the TDP Archive database.


[id="1.0.0-RN3"]
=== Additional tables mirrored from the TDP Archive database

The number of tables in the data warehouse that are mirrored from the TDP 
Archive database has been increased. At the same time, some of the existing
table names have been changed in the data warehouse to match the changes 
introduced to the corresponding tables in the latest release of the TDP Archive
database. In other words, all tables mirrored from the TDP Archive database
have identical names in the data warehouse.

The current selection of tables that are now mirrored from the TDP Archive 
database to th data warehouse can be found in the document:

* Installation of the TDP data warehouse
